name: ubuntu-latest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # - name: Generate token
      #   id: generate_token
      #   uses: tibdex/github-app-token@v1.8
      #   with:
      #     app_id: ${{ secrets.APP_ID }}
      #     private_key: ${{ secrets.PRIVATE_KEY }}

      # - name: Output token
      #   env:
      #     TOKEN: ${{ steps.generate_token.outputs.token }}
      #   run: |
      #     echo "Access Token: ${TOKEN:4}"
      
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set build time
        id: set
        run: echo "build_time=aaa-$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
        
      - name: Build with Maven
        run: mvn clean install -s settings.xml -DskipTests --file pom.xml -Dbuild_time=${{ steps.set.outputs.build_time }}
        env:
          GITHUB_TOKEN: ${{ secrets.READ2 }}
          
      - name: Test
        run: mvn test --file pom.xml -Dbuild_time=${{ steps.set.outputs.build_time }}
